version: '3.9'
services:
  web:
    image: cxsz16888/musicdown:latest
    ports:
      - "8000:8000"
    environment:
      - USE_LIGHT_DOWNLOAD_MODE=${USE_LIGHT_DOWNLOAD_MODE:-false}
    volumes:
      - ./downloads:/app/downloads
      - ./config:/app/config
    restart: unless-stopped
